
-- operations-performance-analytics - Synthetic Portfolio Dataset
-- Run this script inside a PostgreSQL database named:
-- operations_analytics
-- All data generated by this script is synthetic and generic.
-- No real project, company, contractor, location, hostname, IP, vendor,
-- customer, or infrastructure identifier is represented.

BEGIN;

DROP SCHEMA IF EXISTS analytics CASCADE;
CREATE SCHEMA analytics;

-- ============================================================
-- 1) DIMENSIONS
-- ============================================================

CREATE TABLE analytics.dim_date (
    date_key        integer PRIMARY KEY,
    full_date       date NOT NULL UNIQUE,
    day_of_month    smallint NOT NULL,
    day_name        varchar(10) NOT NULL,
    week_of_year    smallint NOT NULL,
    month_number    smallint NOT NULL,
    month_name      varchar(10) NOT NULL,
    quarter_number  smallint NOT NULL,
    year_number     smallint NOT NULL,
    is_weekend      boolean NOT NULL
);

CREATE TABLE analytics.dim_contractor (
    contractor_id    integer PRIMARY KEY,
    contractor_code  varchar(10) NOT NULL UNIQUE,
    contractor_name  varchar(50) NOT NULL,
    service_scope    varchar(100),
    contract_start   date NOT NULL,
    contract_end     date,
    status           varchar(20) NOT NULL
);

CREATE TABLE analytics.dim_site (
    site_id          integer PRIMARY KEY,
    site_code        varchar(20) NOT NULL UNIQUE,
    site_name        varchar(50) NOT NULL,
    location_group   varchar(20) NOT NULL
                     CHECK (location_group IN ('Central','Regional')),
    region_code      varchar(20) NOT NULL,
    site_criticality varchar(20) NOT NULL
                     CHECK (site_criticality IN ('Critical','High','Medium'))
);

CREATE TABLE analytics.dim_device (
    device_id        integer PRIMARY KEY,
    device_code      varchar(20) NOT NULL UNIQUE,
    device_name      varchar(50) NOT NULL,
    device_type      varchar(30) NOT NULL,
    device_model     varchar(30) NOT NULL,
    site_id          integer NOT NULL REFERENCES analytics.dim_site(site_id),
    contractor_id    integer NOT NULL REFERENCES analytics.dim_contractor(contractor_id),
    install_date     date NOT NULL,
    criticality      varchar(20) NOT NULL
                     CHECK (criticality IN ('Critical','High','Medium')),
    device_status    varchar(20) NOT NULL DEFAULT 'Active'
);

-- dim_sla = the contractual/rule definition, not the result for one ticket.
CREATE TABLE analytics.dim_sla (
    sla_id           integer PRIMARY KEY,
    sla_code         varchar(30) NOT NULL UNIQUE,
    sla_name         varchar(100) NOT NULL,
    sla_type         varchar(30) NOT NULL,
    issue_type       varchar(20) NOT NULL,
    priority         varchar(20) NOT NULL,
    location_group   varchar(20) NOT NULL
                     CHECK (location_group IN ('Central','Regional')),
    target_minutes   integer NOT NULL CHECK (target_minutes > 0),
    valid_from       date NOT NULL,
    valid_to         date
);

-- ============================================================
-- 2) FACT TABLES
-- ============================================================

CREATE TABLE analytics.fact_issue (
    issue_id         bigint PRIMARY KEY,
    issue_key        varchar(30) NOT NULL UNIQUE,
    issue_type       varchar(20) NOT NULL
                     CHECK (issue_type IN ('Incident','Task','Problem')),
    contractor_id    integer NOT NULL REFERENCES analytics.dim_contractor(contractor_id),
    device_id        integer REFERENCES analytics.dim_device(device_id),
    priority         varchar(20) NOT NULL
                     CHECK (priority IN ('Critical','High','Medium','Low')),
    severity         varchar(20)
                     CHECK (severity IN ('Critical','High','Medium','Low')),
    category         varchar(30) NOT NULL,
    subcategory      varchar(50),
    root_cause       varchar(80),
    status           varchar(20) NOT NULL,
    summary          varchar(200) NOT NULL,
    created_at       timestamp NOT NULL,
    due_date         timestamp,
    resolved_at      timestamp,
    closed_at        timestamp
);


CREATE TABLE analytics.fact_issue_sla (
    issue_sla_id     bigint PRIMARY KEY,
    issue_id         bigint NOT NULL REFERENCES analytics.fact_issue(issue_id),
    sla_id           integer NOT NULL REFERENCES analytics.dim_sla(sla_id),
    sla_start_at     timestamp NOT NULL,
    sla_stop_at      timestamp,
    UNIQUE(issue_id, sla_id)
);

CREATE TABLE analytics.fact_issue_history (
    history_id       bigint PRIMARY KEY,
    issue_id         bigint NOT NULL REFERENCES analytics.fact_issue(issue_id),
    changed_at       timestamp NOT NULL,
    field_name       varchar(40) NOT NULL,
    old_value        varchar(100),
    new_value        varchar(100),
    changed_by       varchar(50) NOT NULL
);

CREATE INDEX idx_issue_created_at ON analytics.fact_issue(created_at);
CREATE INDEX idx_issue_contractor ON analytics.fact_issue(contractor_id);
CREATE INDEX idx_issue_device ON analytics.fact_issue(device_id);
CREATE INDEX idx_issue_type ON analytics.fact_issue(issue_type);
CREATE INDEX idx_sla_issue ON analytics.fact_issue_sla(issue_id);
CREATE INDEX idx_history_issue ON analytics.fact_issue_history(issue_id);

-- ============================================================
-- 3) DATE DIMENSION: six analytical months + buffer
-- ============================================================

INSERT INTO analytics.dim_date
SELECT
    to_char(d, 'YYYYMMDD')::integer,
    d::date,
    extract(day from d)::smallint,
    trim(to_char(d, 'Day')),
    extract(week from d)::smallint,
    extract(month from d)::smallint,
    trim(to_char(d, 'Month')),
    extract(quarter from d)::smallint,
    extract(year from d)::smallint,
    extract(isodow from d) IN (6,7)
FROM generate_series(
    date '2026-01-01',
    date '2026-07-31',
    interval '1 day'
) AS g(d);

-- ============================================================
-- 4) CONTRACTORS
-- ============================================================

INSERT INTO analytics.dim_contractor VALUES
(1,'CTR-A','Contractor A','Operations and maintenance',date '2025-01-01',date '2027-12-31','Active'),
(2,'CTR-B','Contractor B','Operations and maintenance',date '2025-01-01',date '2027-12-31','Active'),
(3,'CTR-C','Contractor C','Operations and maintenance',date '2025-01-01',date '2027-12-31','Active'),
(4,'CTR-D','Contractor D','Operations and maintenance',date '2025-01-01',date '2027-12-31','Active'),
(5,'CTR-E','Contractor E','Operations and maintenance',date '2025-01-01',date '2027-12-31','Active');

-- ============================================================
-- 5) SITES
-- ============================================================

INSERT INTO analytics.dim_site VALUES
(1,'SITE-C01','Site C01','Central','Central-A','Critical'),
(2,'SITE-C02','Site C02','Central','Central-B','Critical'),
(3,'SITE-C03','Site C03','Central','Central-C','High'),
(4,'SITE-C04','Site C04','Central','Central-D','High'),
(5,'SITE-R01','Site R01','Regional','Region-A','Critical'),
(6,'SITE-R02','Site R02','Regional','Region-B','High'),
(7,'SITE-R03','Site R03','Regional','Region-C','High'),
(8,'SITE-R04','Site R04','Regional','Region-D','Critical'),
(9,'SITE-R05','Site R05','Regional','Region-E','Medium'),
(10,'SITE-R06','Site R06','Regional','Region-F','High'),
(11,'SITE-R07','Site R07','Regional','Region-G','Medium'),
(12,'SITE-R08','Site R08','Regional','Region-H','High');

-- ============================================================
-- 6) DEVICES
-- ============================================================

INSERT INTO analytics.dim_device
SELECT
    gs AS device_id,
    'DEV-' || lpad(gs::text,4,'0') AS device_code,
    CASE ((gs - 1) % 4)
        WHEN 0 THEN 'Server-'   || lpad(gs::text,3,'0')
        WHEN 1 THEN 'Switch-'   || lpad(gs::text,3,'0')
        WHEN 2 THEN 'Router-'   || lpad(gs::text,3,'0')
        ELSE        'Firewall-' || lpad(gs::text,3,'0')
    END AS device_name,
    CASE ((gs - 1) % 4)
        WHEN 0 THEN 'Server'
        WHEN 1 THEN 'Switch'
        WHEN 2 THEN 'Router'
        ELSE        'Firewall'
    END AS device_type,
    CASE
        WHEN ((gs - 1) % 4) = 0 THEN
            CASE WHEN gs % 3 = 0 THEN 'Server-B' ELSE 'Server-A' END
        WHEN ((gs - 1) % 4) = 1 THEN
            CASE WHEN gs % 5 IN (0,1) THEN 'Switch-S2' ELSE 'Switch-S1' END
        WHEN ((gs - 1) % 4) = 2 THEN
            CASE WHEN gs % 3 = 0 THEN 'Router-R2' ELSE 'Router-R1' END
        ELSE
            CASE WHEN gs % 3 = 0 THEN 'Firewall-F2' ELSE 'Firewall-F1' END
    END AS device_model,
    ((gs - 1) % 12) + 1 AS site_id,
    ((gs - 1) % 5) + 1 AS contractor_id,
    date '2021-01-01' + ((gs * 29) % 1400) AS install_date,
    CASE
        WHEN gs % 5 = 0 THEN 'Critical'
        WHEN gs % 3 = 0 THEN 'High'
        ELSE 'Medium'
    END AS criticality,
    'Active'
FROM generate_series(1,96) gs;

-- ============================================================
-- 7) SLA RULES
-- Central: Critical 2h, High 3h, Medium 6h, Low 12h
-- Regional: +5h to each Central target
-- These are synthetic portfolio rules.
-- ============================================================

INSERT INTO analytics.dim_sla VALUES
(1,'RES-CRIT-C','Critical Central Resolution','Resolution','Incident','Critical','Central',120,date '2026-01-01',NULL),
(2,'RES-CRIT-R','Critical Regional Resolution','Resolution','Incident','Critical','Regional',420,date '2026-01-01',NULL),
(3,'RES-HIGH-C','High Central Resolution','Resolution','Incident','High','Central',180,date '2026-01-01',NULL),
(4,'RES-HIGH-R','High Regional Resolution','Resolution','Incident','High','Regional',480,date '2026-01-01',NULL),
(5,'RES-MED-C','Medium Central Resolution','Resolution','Incident','Medium','Central',360,date '2026-01-01',NULL),
(6,'RES-MED-R','Medium Regional Resolution','Resolution','Incident','Medium','Regional',660,date '2026-01-01',NULL),
(7,'RES-LOW-C','Low Central Resolution','Resolution','Incident','Low','Central',720,date '2026-01-01',NULL),
(8,'RES-LOW-R','Low Regional Resolution','Resolution','Incident','Low','Regional',1020,date '2026-01-01',NULL);

-- ============================================================
-- 8) INCIDENTS
-- ============================================================

WITH months AS (
    SELECT generate_series(date '2026-01-01', date '2026-06-01', interval '1 month')::date AS month_start
),
incident_seed AS (
    SELECT
        row_number() OVER (ORDER BY m.month_start, n)::bigint AS rn,
        m.month_start,
        n,
        -- rising volume in later months
        CASE extract(month from m.month_start)::int
            WHEN 1 THEN 72
            WHEN 2 THEN 76
            WHEN 3 THEN 81
            WHEN 4 THEN 88
            WHEN 5 THEN 96
            ELSE 102
        END AS month_count
    FROM months m
    CROSS JOIN generate_series(1,110) n
),
base AS (
    SELECT *
    FROM incident_seed
    WHERE n <= month_count
),
assigned AS (
    SELECT
        rn,
        month_start,
        n,
        CASE
            WHEN extract(month from month_start) >= 4 AND n % 9 = 0
                THEN 8
            ELSE ((rn * 7 + n * 3) % 12)::int + 1
        END AS site_id,
        CASE
            WHEN n % 20 = 0 THEN 'Critical'
            WHEN n % 5 = 0 THEN 'High'
            WHEN n % 2 = 0 THEN 'Medium'
            ELSE 'Low'
        END AS priority
    FROM base
),
with_device AS (
    SELECT
        a.*,
        COALESCE(
            (
                SELECT d.device_id
                FROM analytics.dim_device d
                WHERE d.site_id = a.site_id
                ORDER BY
                    CASE
                        WHEN extract(month from a.month_start) >= 3
                             AND d.device_model = 'Switch-S2' THEN 0
                        ELSE 1
                    END,
                    ((d.device_id * 13 + a.rn)::bigint % 97)
                LIMIT 1
            ),
            1
        ) AS device_id
    FROM assigned a
),
prepared AS (
    SELECT
        w.*,
        d.contractor_id,
        d.device_type,
        d.device_model,
        s.location_group,
        (
            w.month_start::timestamp
            + ((w.n * 2 + w.rn) % 27) * interval '1 day'
            + (6 + ((w.n * 3) % 15)) * interval '1 hour'
            + ((w.n * 11) % 60) * interval '1 minute'
        ) AS created_at,
        CASE
            WHEN w.n % 20 = 0 THEN 'Critical'
            WHEN w.n % 5 = 0 THEN 'High'
            WHEN w.n % 2 = 0 THEN 'Medium'
            ELSE 'Low'
        END AS severity
    FROM with_device w
    JOIN analytics.dim_device d ON d.device_id = w.device_id
    JOIN analytics.dim_site s ON s.site_id = w.site_id
),
categorized AS (
    SELECT
        p.*,
        CASE
            WHEN device_type = 'Switch' AND device_model = 'Switch-S2' AND rn % 3 <> 0 THEN 'Hardware'
            WHEN site_id = 8 AND rn % 2 = 0 THEN 'Power'
            WHEN rn % 13 = 0 THEN 'Security'
            WHEN rn % 11 = 0 THEN 'Configuration'
            WHEN rn % 7 = 0 THEN 'Software'
            WHEN rn % 5 = 0 THEN 'Performance'
            ELSE 'Network'
        END AS category
    FROM prepared p
),
caused AS (
    SELECT
        c.*,
        CASE category
            WHEN 'Hardware' THEN
                CASE WHEN device_model = 'Switch-S2'
                     THEN 'Interface Module Failure'
                     WHEN rn % 2 = 0 THEN 'Power Supply Failure'
                     ELSE 'Hardware Degradation' END
            WHEN 'Power' THEN
                CASE WHEN rn % 3 = 0 THEN 'UPS Failure' ELSE 'Power Outage' END
            WHEN 'Security' THEN
                CASE WHEN rn % 2 = 0 THEN 'Firewall Rule Issue'
                     ELSE 'Certificate Expiration' END
            WHEN 'Configuration' THEN
                CASE WHEN rn % 2 = 0 THEN 'Incorrect Configuration'
                     ELSE 'Configuration Mismatch' END
            WHEN 'Software' THEN
                CASE WHEN rn % 2 = 0 THEN 'Service Crash' ELSE 'Software Bug' END
            WHEN 'Performance' THEN
                CASE WHEN rn % 2 = 0 THEN 'High CPU Usage' ELSE 'Resource Exhaustion' END
            ELSE
                CASE
                    WHEN rn % 4 = 0 THEN 'Interface Failure'
                    WHEN rn % 4 = 1 THEN 'Routing Issue'
                    WHEN rn % 4 = 2 THEN 'Packet Loss'
                    ELSE 'Link Failure'
                END
        END AS root_cause
    FROM categorized c
),
timed AS (
    SELECT
        c.*,
        sla.sla_id,
        sla.target_minutes,
        GREATEST(
            20,
            round(
                sla.target_minutes *
                CASE
                    WHEN contractor_id = 3 AND extract(month from month_start) >= 4
                        THEN (0.90 + ((rn % 70)::numeric / 100))
                    WHEN contractor_id = 3
                        THEN (0.75 + ((rn % 55)::numeric / 100))
                    WHEN contractor_id = 2
                        THEN (0.35 + ((rn % 55)::numeric / 100))
                    ELSE (0.45 + ((rn % 75)::numeric / 100))
                END
            )
        )::int AS resolution_minutes
    FROM caused c
    JOIN analytics.dim_sla sla
      ON sla.issue_type = 'Incident'
     AND sla.priority = c.priority
     AND sla.location_group = c.location_group
)
INSERT INTO analytics.fact_issue (
    issue_id, issue_key, issue_type, contractor_id, device_id,
    priority, severity, category, subcategory, root_cause,
    status, summary, created_at, due_date, resolved_at, closed_at
)
SELECT
    rn,
    'INC-' || lpad(rn::text,6,'0'),
    'Incident',
    contractor_id,
    device_id,
    priority,
    severity,
    category,
    CASE category
        WHEN 'Network' THEN 'Network Service'
        WHEN 'Hardware' THEN 'Equipment'
        WHEN 'Software' THEN 'System Software'
        WHEN 'Configuration' THEN 'Configuration Management'
        WHEN 'Power' THEN 'Power Infrastructure'
        WHEN 'Security' THEN 'Security Control'
        WHEN 'Performance' THEN 'Resource Performance'
        ELSE 'General'
    END,
    root_cause,
    'Closed',
    category || ' incident on ' || device_type,
    created_at,
    NULL,
    created_at + resolution_minutes * interval '1 minute',
    created_at + resolution_minutes * interval '1 minute'
        + (10 + (rn % 50)) * interval '1 minute'
FROM timed;

-- ============================================================
-- 9) SLA EXECUTION FACTS
-- ============================================================

INSERT INTO analytics.fact_issue_sla (
    issue_sla_id, issue_id, sla_id, sla_start_at, sla_stop_at
)
SELECT
    i.issue_id,
    i.issue_id,
    s.sla_id,
    i.created_at,
    i.resolved_at
FROM analytics.fact_issue i
JOIN analytics.dim_device d ON d.device_id = i.device_id
JOIN analytics.dim_site st ON st.site_id = d.site_id
JOIN analytics.dim_sla s
  ON s.issue_type = i.issue_type
 AND s.priority = i.priority
 AND s.location_group = st.location_group
WHERE i.issue_type = 'Incident';

-- ============================================================
-- 10) PLANNED TASKS
-- ============================================================

WITH months AS (
    SELECT generate_series(date '2026-01-01', date '2026-06-01', interval '1 month')::date AS month_start
),
task_seed AS (
    SELECT
        row_number() OVER (ORDER BY m.month_start, c.contractor_id, n)::bigint AS seq,
        m.month_start,
        c.contractor_id,
        n
    FROM months m
    CROSS JOIN analytics.dim_contractor c
    CROSS JOIN generate_series(1,25) n
),
prepared AS (
    SELECT
        t.*,
        (
            t.month_start::timestamp
            + ((t.n - 1) % 18) * interval '1 day'
            + (8 + (t.n % 6)) * interval '1 hour'
        ) AS created_at,
        CASE
            WHEN t.n % 4 = 0 THEN 'Inspection'
            WHEN t.n % 4 = 1 THEN 'Preventive Maintenance'
            WHEN t.n % 4 = 2 THEN 'Routine Check'
            ELSE 'Reporting'
        END AS task_category
    FROM task_seed t
),
timed AS (
    SELECT
        p.*,
        created_at + (3 + (n % 5)) * interval '1 day' AS due_date,
        CASE
            WHEN contractor_id = 4 AND extract(month from month_start) >= 4
                THEN (CASE WHEN n % 3 = 0 THEN 3 WHEN n % 4 = 0 THEN 2 ELSE -1 END)
            WHEN contractor_id = 4
                THEN (CASE WHEN n % 5 = 0 THEN 2 ELSE -1 END)
            WHEN contractor_id = 2
                THEN (CASE WHEN n % 10 = 0 THEN 1 ELSE -2 END)
            ELSE
                (CASE WHEN n % 8 = 0 THEN 1 ELSE -1 END)
        END AS delay_days
    FROM prepared p
)
INSERT INTO analytics.fact_issue (
    issue_id, issue_key, issue_type, contractor_id, device_id,
    priority, severity, category, subcategory, root_cause,
    status, summary, created_at, due_date, resolved_at, closed_at
)
SELECT
    100000 + seq,
    'TSK-' || lpad(seq::text,6,'0'),
    'Task',
    contractor_id,
    CASE
        WHEN task_category = 'Reporting' THEN NULL
        ELSE ((seq * 11 + contractor_id) % 96)::int + 1
    END,
    'Medium',
    'Medium',
    'Maintenance',
    task_category,
    NULL,
    'Closed',
    task_category || ' task',
    created_at,
    due_date,
    due_date + delay_days * interval '1 day',
    due_date + delay_days * interval '1 day' + interval '30 minutes'
FROM timed;

-- ============================================================
-- 11) ISSUE HISTORY
-- ============================================================

WITH incidents AS (
    SELECT *
    FROM analytics.fact_issue
    WHERE issue_type = 'Incident'
),
events AS (
    SELECT issue_id, created_at + interval '5 minutes' AS changed_at,
           'status'::varchar AS field_name, 'Open'::varchar AS old_value,
           'Assigned'::varchar AS new_value, 'system-user'::varchar AS changed_by
    FROM incidents

    UNION ALL

    SELECT issue_id, created_at + interval '20 minutes',
           'status', 'Assigned', 'In Progress',
           'contractor-user'
    FROM incidents

    UNION ALL

    SELECT issue_id, resolved_at,
           'status', 'In Progress', 'Resolved',
           'contractor-user'
    FROM incidents

    UNION ALL

    SELECT issue_id, closed_at,
           'status', 'Resolved', 'Closed',
           'operations-user'
    FROM incidents
),
numbered AS (
    SELECT
        row_number() OVER (ORDER BY issue_id, changed_at, new_value)::bigint AS history_id,
        *
    FROM events
)
INSERT INTO analytics.fact_issue_history
(history_id, issue_id, changed_at, field_name, old_value, new_value, changed_by)
SELECT history_id, issue_id, changed_at, field_name, old_value, new_value, changed_by
FROM numbered;

WITH tasks AS (
    SELECT *
    FROM analytics.fact_issue
    WHERE issue_type = 'Task'
),
events AS (
    SELECT issue_id, created_at AS changed_at,
           'status'::varchar AS field_name, NULL::varchar AS old_value,
           'Open'::varchar AS new_value, 'operations-user'::varchar AS changed_by
    FROM tasks

    UNION ALL

    SELECT issue_id, created_at + interval '1 day',
           'status', 'Open', 'In Progress',
           'contractor-user'
    FROM tasks

    UNION ALL

    SELECT issue_id, resolved_at,
           'status', 'In Progress', 'Resolved',
           'contractor-user'
    FROM tasks

    UNION ALL

    SELECT issue_id, closed_at,
           'status', 'Resolved', 'Closed',
           'operations-user'
    FROM tasks
),
base_id AS (
    SELECT COALESCE(max(history_id),0) AS mx
    FROM analytics.fact_issue_history
),
numbered AS (
    SELECT
        b.mx + row_number() OVER (ORDER BY e.issue_id, e.changed_at, e.new_value)::bigint AS history_id,
        e.*
    FROM events e
    CROSS JOIN base_id b
)
INSERT INTO analytics.fact_issue_history
(history_id, issue_id, changed_at, field_name, old_value, new_value, changed_by)
SELECT history_id, issue_id, changed_at, field_name, old_value, new_value, changed_by
FROM numbered;

COMMIT;

-- ============================================================
-- 12) DATA QUALITY / VALIDATION QUERIES
-- ============================================================

-- Table row counts
SELECT 'dim_date' AS table_name, count(*) AS row_count FROM analytics.dim_date
UNION ALL SELECT 'dim_contractor', count(*) FROM analytics.dim_contractor
UNION ALL SELECT 'dim_site', count(*) FROM analytics.dim_site
UNION ALL SELECT 'dim_device', count(*) FROM analytics.dim_device
UNION ALL SELECT 'dim_sla', count(*) FROM analytics.dim_sla
UNION ALL SELECT 'fact_issue', count(*) FROM analytics.fact_issue
UNION ALL SELECT 'fact_issue_sla', count(*) FROM analytics.fact_issue_sla
UNION ALL SELECT 'fact_issue_history', count(*) FROM analytics.fact_issue_history
ORDER BY table_name;

-- Basic issue sanity checks
SELECT
    count(*) FILTER (WHERE resolved_at < created_at) AS invalid_resolution_dates,
    count(*) FILTER (WHERE due_date IS NOT NULL AND issue_type <> 'Task') AS unexpected_due_dates
FROM analytics.fact_issue;

-- Six-month issue distribution (validation only)
SELECT
    date_trunc('month', created_at)::date AS month,
    issue_type,
    count(*) AS records
FROM analytics.fact_issue
GROUP BY 1,2
ORDER BY 1,2;


